-- Create a db with a state TABLE
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.states(id INT UNIQUE NULL AUTO_INCREMENT PRIMARY KEY, UNIQUE(ID), name VARCHAR(256) NOT NULL);